"""sqlite_initial

Revision ID: 7c8043b713ef
Revises:
"""
from alembic import op
import sqlalchemy as sa


revision = '7c8043b713ef'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('address', sa.String(length=300), nullable=False),
    sa.Column('phone', sa.String(length=60), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('approval_mode', sa.String(length=20), nullable=False),
    sa.Column('route', sa.JSON(), nullable=False),
    sa.Column('route_version', sa.Integer(), nullable=False),
    sa.Column('next_number', sa.Integer(), nullable=False),
    sa.Column('next_invoice', sa.Integer(), server_default='1', nullable=False),
    sa.Column('seal_default', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('registration_number', sa.String(length=14), server_default='', nullable=False),
    sa.Column('bank_details', sa.String(length=500), server_default='', nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_companies'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=300), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('contact', sa.String(length=120), nullable=False),
    sa.Column('address', sa.String(length=300), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_customers_company_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customers')),
    sa.UniqueConstraint('company_id', 'id', name=op.f('uq_customers_company_id_id'))
    )
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_departments_company_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_departments')),
    sa.UniqueConstraint('company_id', 'id', name=op.f('uq_departments_company_id_id')),
    sa.UniqueConstraint('company_id', 'name', name=op.f('uq_departments_company_id_name'))
    )
    op.create_table('seals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('image', sa.LargeBinary(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_seals_company_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_seals')),
    sa.UniqueConstraint('company_id', 'id', name=op.f('uq_seals_company_id_id'))
    )
    op.create_index(op.f('ix_seals_company_id'), 'seals', ['company_id'], unique=False)
    op.create_table('sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['company_id', 'department_id'], ['departments.company_id', 'departments.id'], name=op.f('fk_sections_company_id_department_id_departments')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_sections_company_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sections')),
    sa.UniqueConstraint('company_id', 'department_id', 'id', name=op.f('uq_sections_company_id_department_id_id')),
    sa.UniqueConstraint('company_id', 'id', name=op.f('uq_sections_company_id_id'))
    )
    op.create_table('memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['company_id', 'department_id', 'section_id'], ['sections.company_id', 'sections.department_id', 'sections.id'], name=op.f('fk_memberships_company_id_department_id_section_id_sections')),
    sa.ForeignKeyConstraint(['company_id', 'department_id'], ['departments.company_id', 'departments.id'], name=op.f('fk_memberships_company_id_department_id_departments')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_memberships_company_id_companies')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_memberships_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memberships')),
    sa.UniqueConstraint('company_id', 'id', name=op.f('uq_memberships_company_id_id')),
    sa.UniqueConstraint('company_id', 'user_id', name=op.f('uq_memberships_company_id_user_id'))
    )
    op.create_table('login_sessions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('membership_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['membership_id'], ['memberships.id'], name=op.f('fk_login_sessions_membership_id_memberships')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_login_sessions'))
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('customer_contact', sa.String(length=120), nullable=False),
    sa.Column('customer_corporate_number', sa.String(length=13), nullable=False),
    sa.Column('status', sa.String(length=25), nullable=False),
    sa.Column('due_on', sa.Date(), nullable=True),
    sa.Column('external_url', sa.String(length=1000), nullable=False),
    sa.Column('lock_version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id', 'customer_id'], ['customers.company_id', 'customers.id'], name=op.f('fk_projects_company_id_customer_id_customers')),
    sa.ForeignKeyConstraint(['company_id', 'department_id', 'section_id'], ['sections.company_id', 'sections.department_id', 'sections.id'], name=op.f('fk_projects_company_id_department_id_section_id_sections')),
    sa.ForeignKeyConstraint(['company_id', 'department_id'], ['departments.company_id', 'departments.id'], name=op.f('fk_projects_company_id_department_id_departments')),
    sa.ForeignKeyConstraint(['company_id', 'owner_id'], ['memberships.company_id', 'memberships.id'], name=op.f('fk_projects_company_id_owner_id_memberships')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_projects_company_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects')),
    sa.UniqueConstraint('company_id', 'id', name=op.f('uq_projects_company_id_id'))
    )
    op.create_index(op.f('ix_projects_company_id'), 'projects', ['company_id'], unique=False)
    op.create_table('project_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('upload_id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=200), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('content', sa.LargeBinary(), nullable=False),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('size_bytes > 0', name=op.f('ck_project_attachments_positive_size')),
    sa.ForeignKeyConstraint(['company_id', 'project_id'], ['projects.company_id', 'projects.id'], name=op.f('fk_project_attachments_company_id_project_id_projects')),
    sa.ForeignKeyConstraint(['company_id', 'uploaded_by_id'], ['memberships.company_id', 'memberships.id'], name=op.f('fk_project_attachments_company_id_uploaded_by_id_memberships')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_project_attachments_company_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_attachments')),
    sa.UniqueConstraint('company_id', 'project_id', 'upload_id', name=op.f('uq_project_attachments_company_id_project_id_upload_id'))
    )
    op.create_index(op.f('ix_project_attachments_company_id'), 'project_attachments', ['company_id'], unique=False)
    op.create_index(op.f('ix_project_attachments_project_id'), 'project_attachments', ['project_id'], unique=False)
    op.create_table('quotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=40), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sales_status', sa.String(length=20), server_default='open', nullable=False),
    sa.Column('sales_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('sent_on', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['company_id', 'creator_id'], ['memberships.company_id', 'memberships.id'], name=op.f('fk_quotes_company_id_creator_id_memberships')),
    sa.ForeignKeyConstraint(['company_id', 'department_id', 'section_id'], ['sections.company_id', 'sections.department_id', 'sections.id'], name=op.f('fk_quotes_company_id_department_id_section_id_sections')),
    sa.ForeignKeyConstraint(['company_id', 'department_id'], ['departments.company_id', 'departments.id'], name=op.f('fk_quotes_company_id_department_id_departments')),
    sa.ForeignKeyConstraint(['company_id', 'owner_id'], ['memberships.company_id', 'memberships.id'], name=op.f('fk_quotes_company_id_owner_id_memberships')),
    sa.ForeignKeyConstraint(['company_id', 'project_id'], ['projects.company_id', 'projects.id'], name=op.f('fk_quotes_company_id_project_id_projects')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_quotes_company_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quotes')),
    sa.UniqueConstraint('company_id', 'id', name=op.f('uq_quotes_company_id_id')),
    sa.UniqueConstraint('company_id', 'number', name=op.f('uq_quotes_company_id_number'))
    )
    op.create_index(op.f('ix_quotes_company_id'), 'quotes', ['company_id'], unique=False)
    op.create_index(op.f('ix_quotes_project_id'), 'quotes', ['project_id'], unique=False)
    op.create_table('requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('acceptance', sa.Text(), nullable=False),
    sa.Column('questions', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('agreement', sa.JSON(), nullable=True),
    sa.Column('lock_version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id', 'project_id'], ['projects.company_id', 'projects.id'], name=op.f('fk_requirements_company_id_project_id_projects')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_requirements_company_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_requirements')),
    sa.UniqueConstraint('company_id', 'id', name=op.f('uq_requirements_company_id_id'))
    )
    op.create_index(op.f('ix_requirements_company_id'), 'requirements', ['company_id'], unique=False)
    op.create_index(op.f('ix_requirements_project_id'), 'requirements', ['project_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=True),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id', 'actor_id'], ['memberships.company_id', 'memberships.id'], name=op.f('fk_audit_logs_company_id_actor_id_memberships')),
    sa.ForeignKeyConstraint(['company_id', 'quote_id'], ['quotes.company_id', 'quotes.id'], name=op.f('fk_audit_logs_company_id_quote_id_quotes')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_audit_logs_company_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_table('requirement_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('requirement_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('note', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id', 'actor_id'], ['memberships.company_id', 'memberships.id'], name=op.f('fk_requirement_history_company_id_actor_id_memberships')),
    sa.ForeignKeyConstraint(['company_id', 'requirement_id'], ['requirements.company_id', 'requirements.id'], name=op.f('fk_requirement_history_company_id_requirement_id_requirements')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_requirement_history_company_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_requirement_history')),
    sa.UniqueConstraint('company_id', 'requirement_id', 'version', name=op.f('uq_requirement_history_company_id_requirement_id_version'))
    )
    op.create_table('revisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('lock_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=25), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=16, scale=0), nullable=False),
    sa.Column('tax', sa.Numeric(precision=16, scale=0), nullable=False),
    sa.Column('total', sa.Numeric(precision=16, scale=0), nullable=False),
    sa.Column('pdf', sa.LargeBinary(), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id', 'quote_id'], ['quotes.company_id', 'quotes.id'], name=op.f('fk_revisions_company_id_quote_id_quotes')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_revisions_company_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_revisions')),
    sa.UniqueConstraint('company_id', 'id', name=op.f('uq_revisions_company_id_id')),
    sa.UniqueConstraint('company_id', 'quote_id', 'id', name=op.f('uq_revisions_company_id_quote_id_id')),
    sa.UniqueConstraint('company_id', 'quote_id', 'version', name=op.f('uq_revisions_company_id_quote_id_version'))
    )
    op.create_index(op.f('ix_revisions_quote_id'), 'revisions', ['quote_id'], unique=False)
    op.create_table('approval_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('revision_id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('route_version', sa.Integer(), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=25), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id', 'requester_id'], ['memberships.company_id', 'memberships.id'], name=op.f('fk_approval_requests_company_id_requester_id_memberships')),
    sa.ForeignKeyConstraint(['company_id', 'revision_id'], ['revisions.company_id', 'revisions.id'], name=op.f('fk_approval_requests_company_id_revision_id_revisions')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_approval_requests_company_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approval_requests')),
    sa.UniqueConstraint('company_id', 'id', name=op.f('uq_approval_requests_company_id_id'))
    )
    op.create_index(op.f('ix_approval_requests_revision_id'), 'approval_requests', ['revision_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=False),
    sa.Column('revision_id', sa.Integer(), nullable=False),
    sa.Column('ordered_on', sa.Date(), nullable=False),
    sa.Column('delivery_on', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('lock_version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id', 'quote_id', 'revision_id'], ['revisions.company_id', 'revisions.quote_id', 'revisions.id'], name=op.f('fk_orders_company_id_quote_id_revision_id_revisions')),
    sa.ForeignKeyConstraint(['company_id', 'quote_id'], ['quotes.company_id', 'quotes.id'], name=op.f('fk_orders_company_id_quote_id_quotes')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_orders_company_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders')),
    sa.UniqueConstraint('company_id', 'id', name=op.f('uq_orders_company_id_id')),
    sa.UniqueConstraint('company_id', 'quote_id', name=op.f('uq_orders_company_id_quote_id'))
    )
    op.create_table('approval_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('approver_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=25), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id', 'approver_id'], ['memberships.company_id', 'memberships.id'], name=op.f('fk_approval_steps_company_id_approver_id_memberships')),
    sa.ForeignKeyConstraint(['company_id', 'request_id'], ['approval_requests.company_id', 'approval_requests.id'], name=op.f('fk_approval_steps_company_id_request_id_approval_requests')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_approval_steps_company_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approval_steps')),
    sa.UniqueConstraint('company_id', 'request_id', 'position', name=op.f('uq_approval_steps_company_id_request_id_position'))
    )
    op.create_index(op.f('ix_approval_steps_request_id'), 'approval_steps', ['request_id'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('total', sa.Numeric(precision=16, scale=0), nullable=False),
    sa.Column('issue_on', sa.Date(), nullable=False),
    sa.Column('transaction_on', sa.Date(), nullable=False),
    sa.Column('due_on', sa.Date(), nullable=False),
    sa.Column('paid_on', sa.Date(), nullable=True),
    sa.Column('payment_note', sa.Text(), nullable=False),
    sa.Column('pdf', sa.LargeBinary(), nullable=True),
    sa.Column('lock_version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id', 'order_id'], ['orders.company_id', 'orders.id'], name=op.f('fk_invoices_company_id_order_id_orders')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_invoices_company_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoices')),
    sa.UniqueConstraint('company_id', 'id', name=op.f('uq_invoices_company_id_id')),
    sa.UniqueConstraint('company_id', 'number', name=op.f('uq_invoices_company_id_number'))
    )
    op.create_index('uq_invoices_active_order', 'invoices', ['company_id', 'order_id'], unique=True, sqlite_where=sa.text("status <> 'void'"))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_invoices_active_order', table_name='invoices', sqlite_where=sa.text("status <> 'void'"))
    op.drop_table('invoices')
    op.drop_index(op.f('ix_approval_steps_request_id'), table_name='approval_steps')
    op.drop_table('approval_steps')
    op.drop_table('orders')
    op.drop_index(op.f('ix_approval_requests_revision_id'), table_name='approval_requests')
    op.drop_table('approval_requests')
    op.drop_index(op.f('ix_revisions_quote_id'), table_name='revisions')
    op.drop_table('revisions')
    op.drop_table('requirement_history')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_requirements_project_id'), table_name='requirements')
    op.drop_index(op.f('ix_requirements_company_id'), table_name='requirements')
    op.drop_table('requirements')
    op.drop_index(op.f('ix_quotes_project_id'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_company_id'), table_name='quotes')
    op.drop_table('quotes')
    op.drop_index(op.f('ix_project_attachments_project_id'), table_name='project_attachments')
    op.drop_index(op.f('ix_project_attachments_company_id'), table_name='project_attachments')
    op.drop_table('project_attachments')
    op.drop_index(op.f('ix_projects_company_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_table('login_sessions')
    op.drop_table('memberships')
    op.drop_table('sections')
    op.drop_index(op.f('ix_seals_company_id'), table_name='seals')
    op.drop_table('seals')
    op.drop_table('departments')
    op.drop_table('customers')
    op.drop_table('users')
    op.drop_table('companies')
    # ### end Alembic commands ###
